### ISSUE TITLE
Remove usage ASM

### ISSUE THREAD

**Issue by DJs3000** [cinelerra-cv-team/cinelerra-cv#3]
Is it possible to abandon the use of assembler? This will allow Cinelerra to be used on rare architectures.

**Comment by petterreinholdtsen** [comment]
[DJs3000]
> Is it possible to abandon the use of assembler? This will allow
> Cinelerra to be used on rare architectures.

Anything is possible with good patches.  :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by psemiletov** [comment]
NASM is needed for FFMPEG, but can be replaced with YASM. But actually, asm can be removed if use the exteral libavcodec/FFMPEG.

**Comment by DJs3000** [comment]
> NASM is needed for FFMPEG, but can be replaced with YASM. But actually, asm can be removed if use the exteral libavcodec/FFMPEG.

It would be nice if an external ffmpeg could be used. I have ffmpeg in my system, but I can't use assembler for some reason.

**Comment by FabioLolix** [comment]
> It would be nice if an external ffmpeg could be used

There is a configure flag for that but it is failing to build, the bundled ffmpeg is between 15 and almost 20 years old (0.4.9-pre1 was released on 2004-07-09 seems; the code bundled if after that but before 0.5)

**Comment by DJs3000** [comment]
> > It would be nice if an external ffmpeg could be used
> 
> There is a configure flag for that but it is failing to build, the bundled ffmpeg is between 15 and almost 20 years old (0.4.9-pre1 was released on 2004-07-09 seems; the code bundled if after that but before 0.5)

i use ffmpeg 7.0. Configuring the project "./configure --with-external-ffmpeg", but still need nasm :(
I can build the most recent ffmpeg without an assembler "./configure --prefix=/usr --disable-asm"
