### ISSUE TITLE
Upstream source for libmpeg3?

### ISSUE THREAD

**Issue by petterreinholdtsen** [cinelerra-cv-team/cinelerra-cv#6]
Is there a good upstream source for libmpeg3?  The Debian package, https://tracker.debian.org/pkg/libmpeg3 , might end up being removed because of a dead upstream.  I notice a copy of it is in Cinelerra, and wondered if there is any interest here in taking over the upstream development of this library.

**Comment by petterreinholdtsen** [comment]
Forgot to mention, the Debian package got 11 patches applied to the library that should most likely all go upstream, se https://udd.debian.org/patches.cgi?src=libmpeg3&version=1.8.dfsg-6 for the current list.

**Comment by IgorVladimirsky** [comment]
It looks like 1.8 is the latest version.
Some links:
https://launchpad.net/ubuntu/+source/libmpeg3
Sergio's repo https://github.com/sergiomb2/libmpeg3/commits/master/
https://packages.gentoo.org/packages/media-libs/libmpeg3/bugs

**Comment by petterreinholdtsen** [comment]
[Igor Vladimirsky]
> It looks like 1.8 is the latest version.

I know.  My question is really who can make a 1.9 version. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by IgorVladimirsky** [comment]
Libmpeg3 has been waiting for a hero from the future.

**Comment by petterreinholdtsen** [comment]
[Igor Vladimirsky]
> Libmpeg3 has been waiting for a hero from the future.

Perhaps it is you and you just do not know it yet?

Igor, just for the record, your email provider reject emails from me, so
I can not send emails directly to you.  Mentioning it here, in the hope
that this might reach you.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Igor Vladimirsky]
> Petter, try sending an email from gmail. Or use the contact form on
> [my blog](https://linuxvideoediting.blogspot.com)

I would not dream of sharing my whereabouts, usage times or anything
else with Google, so sending from gmail is not on the table.  If you
want to talk to me me, get a mail service that do not throw away my
emails or ping me on IRC. :)

In any case, I am not really involved in Cinelerra any more and do not
have much to input here, so do not worry about me.

-- 
Happy hacking
Petter Reinholdtsen
